### ISSUE TITLE
tiny_tds fails compiling with "libiconv is missing" error

### ISSUE THREAD

**Issue by fchampreux** [rails-sqlserver/tiny_tds#157]
Hi,
I installed Ruby 2.0.0 on Windows x64 from rubyinstaller-2.0.0-p451-x64.exe
Then DevKit from DevKit-mingw64-64-4.7.2-20130224-1432-sfx.exe
ThenI tried to gem install tiny_tds, with no success.
So I also installed libiconv-1.9.2-1.exe, then run gem install tiny_tds again: no success
I tried to specify the path to libiconv: 
gem install tiny_tds -- --with-iconv-dir=e:/gnuwin32 with no success
Looking at the mkmf.log, it searches in the correct directory, but functions returns errors:

```
"x86_64-w64-mingw32-gcc -o conftest.exe -IE:/Ruby200/include/ruby-2.0.0/x64-mingw32 -IE:/Ruby200/include/ruby-2.0.0/ruby/backward -IE:/Ruby200/include/ruby-2.0.0 -I. -IE:/DevKit/include -IE:/DevKit/mingw/include -IE:/Ruby200/include -Ie:/gnuwin32/include -DFD_SETSIZE=2048 -D_WIN32_WINNT=0x0501 -D_FILE_OFFSET_BITS=64   -O3 -fno-omit-frame-pointer -fno-fast-math -g -Wall -Wextra -Wno-unused-parameter -Wno-parentheses -Wno-long-long -Wno-missing-field-initializers -Wunused-variable -Wpointer-arith -Wwrite-strings -Wdeclaration-after-statement -Wimplicit-function-declaration  conftest.c  -L. -LE:/Ruby200/lib -LE:/DevKit/lib -LE:/DevKit/mingw/lib -LE:/Ruby200/lib -Le:/git/lib -Le:/gnuwin32/ -L.       -lx64-msvcrt-ruby200  -lshell32 -lws2_32 -limagehlp -lshlwapi   "
conftest.c: In function 't':
conftest.c:9:32: warning: variable 'p' set but not used [-Wunused-but-set-variable]
C:\Users\ADMINI~1\AppData\Local\Temp\cccAutis.o: In function `t':
E:\Ruby200\lib\ruby\gems\2.0.0\gems\tiny_tds-0.6.1\ext\tiny_tds/conftest.c:9: undefined reference to `__imp_libiconv_open'
collect2.exe: error: ld returned 1 exit status
checked program was:
/* begin */
 1: #include "ruby.h"
 2: 
 3: #include <winsock2.h>
 4: #include <windows.h>
 5: #include <iconv.h>
 6: 
 7: /*top*/
 8: extern int t(void);
 9: int t(void) { void ((*volatile p)()); p = (void ((*)()))iconv_open; return 0; }
10: int main(int argc, char **argv)
11: {
12:   if (argc > 1000000) {
13:     printf("%p", &t);
14:   }
15: 
16:   return 0;
17: }
/* end */
```

Your help will be highly appreciated !

Thanks,

Fred

**Comment by ginolon** [comment]
0.6.3rc1 and ":github => 'rails-sqlserver/tiny_tds', :branch => 'master'" doesn't work with rubyinstaller 2.1 on Windows 8.1.

Please help. :dancer: 

Thanks.

**Comment by larskanis** [comment]
@ginolon Check out https://github.com/rails-sqlserver/tiny_tds/pull/207 :
```
git clone https://github.com/larskanis/tiny_tds.git
cd tiny_tds
git checkout rake-compiler-dock
rake gem
gem inst pkg/tiny_tds-0.6.3.rc1.gem
```
This should download and install all dependencies. And it should equally work per Gemfile.

**Comment by dharmdip** [comment]
i am keep getting this error

**Comment by dharmdip** [comment]
Keep getting this error for this command, provided proper path as well. 

I am doing this on windows 2012 R2 servers.

Ruby : ruby 2.1.6p336 (2015-04-13 revision 50298) [x64-mingw32]

```
gem install tiny_tds --pre --no-ri --no-rdoc -- --with-freetds-include=C:\freetds-0.95rc2\include --with-freetds-lib=C:\freetds-0.95rc2\lib --with-iconv-include=C:\Utility\libiconv-1.9.2\include --with-iconv-lib=C:\Utility\libiconv-1.9.2\lib

```

ERROR:  Error installing tiny_tds:
ERROR: Failed to build gem native extension.

checking for iconv_open() in iconv.h... no
checking for iconv_open() in -liconv... no
-----
libiconv is missing.
-----

Thanks, 
Dharmdip

**Comment by metaskills** [comment]
This will be solved when #207 is done.

**Comment by dharmdip** [comment]
Thanks you. 

Okay, that's great.. i surpass this error but while custom build i checked this code. 

```
FREETDS_VERSION_INFO = Hash.new { |h,k|
  h[k] = {:files => "ftp://ftp.freetds.org/pub/freetds/stable/freetds-#{k}.tar.gz"}
}.merge({
  "0.82" => {:files => "ftp://ftp.freetds.org/pub/freetds/old/0.82/freetds-0.82.tar.gz"},
  "0.91" => {:files => "ftp://ftp.freetds.org/pub/freetds/stable/freetds-0.91.112.tar.gz"},
  "current" => {:files => "ftp://ftp.freetds.org/pub/freetds/current/freetds-current.tar.gz"}
})
```
source is no longer available and it is moved to git.

**Comment by metaskills** [comment]
I knew the code is on GitHub. Are you telling me the FTP site is down intentionally? I did not think FreeTDS' github mirror was even tagged properly for releases?

**Comment by dharmdip** [comment]
yes, FTP is down.

**Comment by metaskills** [comment]
> FTP is down.

I knew that. See #207. It has happened before and just waiting for it to come back up.

**Comment by dharmdip** [comment]
oh ! okay.. because libiconv and openssl works file and i was keep getting error for this. 
I have changed in code and point to the Git for testing.

**Comment by metaskills** [comment]
That's good, but we can not use GitHub because they do not tag versions there. Thanks tho!

**Comment by dharmdip** [comment]
Yes true. 
Thank you,  for your valuable time. I am going to test against different versions.

**Comment by dharmdip** [comment]
Hi @metaskills, 

i am getting this error while connecting azure, any thought?

`
tiny_tds-0.6.3.rc2-x64-mingw32/lib/tiny_tds/client.rb:74:in `connect': Write to the server failed (TinyTds::Error)

`
Thanks, 
Dharmdip
