### ISSUE TITLE
ArgumentError: argument out of range

### ISSUE THREAD

**Issue by TLmaK0** [rails-sqlserver/tiny_tds#260]
If I run in a rails console with tiny_tds 0.7.0:
```
connection = TinyTds::Client.new(:dataserver=>'server_connection', :database=>'mydatabase',:username=>'myuser',:password=>'mypass')
result = connection.execute("select CONVERT(datetime, '2016/01/28 15:34:13', 120) as date")
result.to_a
```
I get
```
ArgumentError: argument out of range
```

this is the tsql -C response:

```
                           Version: freetds v0.95.20
             freetds.conf directory: /etc/freetds
     MS db-lib source compatibility: no
        Sybase binary compatibility: no
                      Thread safety: yes
                      iconv library: yes
                        TDS version: 5.0
                              iODBC: no
                           unixodbc: no
              SSPI "trusted" logins: no
                           Kerberos: no
                            OpenSSL: no
                             GnuTLS: no
```

and this the freetds.conf

```
[global]
  client charset = UTF-8
  tds version = 7.1
  use utf-16 = true
[server_connection]
        host = myhost
```

and the sqlserver version is SQLServer 2008 R2 10.50.1600.1

Is there something more that I can do to troubleshooting the error?

**Comment by metaskills** [comment]
Could you use the latest TinyTDS release beta at v0.9.5.beta.12. I know for a fact some of those errors were fixed when using certain data types on certain platforms. 

Also, I noticed you using 0.95 of FreeTDS, but your patch level is 20. Latest TinyTDS requires patch level 74 tho I recommend 80 or whatever is current.

**Comment by TLmaK0** [comment]
Thanks @metaskills, I will test it.

**Comment by TLmaK0** [comment]
@metaskills I'm using ruby 1.9.3. I have tried to change gem requirement but I get ```./tiny_tds_ext.h:10:25: fatal error: ruby/thread.h: No such file or directory``` Is there a way to workaround ruby 2.0 requirement?

**Comment by TLmaK0** [comment]
Installing v0.9.5.beta.12 gem returns:
```
result.c:292:15: error: unknown type name ‘DBDATEREC2’
               DBDATEREC2 dr2;
```

**Comment by metaskills** [comment]
Did you upgrade FreeTDS past v0.95.20?

**Comment by TLmaK0** [comment]
Thanks, that was the problem. I will continue with the proves. Removing ruby 2.0 requirement and #include <ruby/thread.h> from tiny_tds_ext.h I was able to compile for ruby 1.9.2.

**Comment by TLmaK0** [comment]
@metaskills Works perfectly with v0.9.5.beta.12, FreeTDS 0.95.80 and Ruby 1.9.2
Do you think it is posible to remove ```#include <ruby/thread.h>``` and ```s.required_ruby_version = '>= 2.0.0'``` from the tiny_tds?

**Comment by metaskills** [comment]
Sorry @TLmaK0, supporting 1.9.3 is not that straight forward. Our build systems for Windows are not really geared towards it now. Feel free to fork this repo, edit, and bundle to it as needed.
